### PR TITLE
Actually fix #537

### LINKED ISSUE #537: latest 0.18.0-SNAPSHOT broken:  No matching ctor found for class java.net.InetSocketAddress
Looks like a new version of 0.18.0-SNAPSHOT was pushed today that breaks cider-nrepl. 0.17.0 isn't affected, nor was 0.18.0-SNAPSHOT prior to today.

```
java -version
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

```
/usr/local/bin/clojure -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} refactor-nrepl {:mvn/version "2.4.0-SNAPSHOT"} cider/cider-nrepl {:mvn/version "0.18.0-SNAPSHOT"}}}'  -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"])'
Exception in thread "main" java.lang.IllegalArgumentException: No matching ctor found for class java.net.InetSocketAddress
        at clojure.lang.Reflector.invokeConstructor(Reflector.java:183)
        at clojure.tools.nrepl.server$start_server.invokeStatic(server.clj:141)
        at clojure.tools.nrepl.server$start_server.doInvoke(server.clj:121)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at cider_nrepl.main$start_nrepl.invokeStatic(main.clj:39)
        at cider_nrepl.main$start_nrepl.invoke(main.clj:31)
        at cider_nrepl.main$init.invokeStatic(main.clj:55)
        at cider_nrepl.main$init.invoke(main.clj:51)
        at user$eval1096.invokeStatic(NO_SOURCE_FILE:1)
        at user$eval1096.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7025)
        at clojure.core$eval.invokeStatic(core.clj:3206)
        at clojure.main$eval_opt.invokeStatic(main.clj:291)
        at clojure.main$eval_opt.invoke(main.clj:285)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
```

### PR DESCRIPTION
**Pull request by hagmonk**
My fix yesterday was not properly tested - I started nREPL from the command line, but I didn't attempt to exercise it with messages. As a result, I missed the fact I was setting passing the middleware as the handler, which kept things just as broken.

This PR contains a fix for that problem, plus a new test ns `cider.nrepl.main-test` that exercises the `start-nrepl` function by passing it a variety of valid and invalid option maps. The tests go as far as checking that two `:op "clone"` messages can be exchanged before declaring success.

On my local machine I saw a test failure in a totally unrelated part of the code, `test-sum-types-is-base64`, which I'm assuming is an artifact of my local environment and not something that will come up in the PR tests.

### CODE REVIEW

File: test/clj/cider/nrepl/main_test.clj [hunk 1]
```diff
@@ -0,0 +1,43 @@
+(ns cider.nrepl.main-test
+  (:require [cider.nrepl :refer [wrap-debug cider-middleware]]
+            [cider-nrepl.main :as m]
+            [clojure.test :refer :all]
+            [clojure.tools.nrepl :as nrepl]
+            [clojure.tools.nrepl.server :as nrepl.server]
+            [clojure.tools.nrepl.transport :as transport]))
+
+(defn start-stop-nrepl-session [opts]
```
Comment (bbatsov) [inline test/clj/cider/nrepl/main_test.clj]: I don't see where you stop the server in each test.

File: src/cider_nrepl/main.clj [hunk 2]
```diff
@@ -28,17 +28,36 @@
   [middleware-var-strs]
   (into [] mw-xf middleware-var-strs))
 
+(defn- build-handler
```
Comment (bbatsov) [inline src/cider_nrepl/main.clj]: I think that build handler should just take a list of middlewares and be invoked only if a handler wasn't passed to `start-nrepl`.

File: src/cider_nrepl/main.clj [hunk 3]
```diff
@@ -28,17 +28,36 @@
...
 
-        handler (cond-> (or handler nrepl.server/default-handler)
-                  middleware (apply (->mw-list middleware)))
+   * :middleware - a sequence of vars or string which can be resolved to vars,
+     representing middleware you wish to mix in to the nREPL handler. Vars can
+     resolve to a sequence of vars, in which case they'll be flattened into the
+     list of middleware."
+  [{:keys [bind port] :as opts}]
+  (let [handler
+        (build-handler opts)
```
Comment (bbatsov) [inline src/cider_nrepl/main.clj]: Here I'd `(or handler (build-handler)`. (provided it's extracted from the `ops` map above.

File: src/cider_nrepl/main.clj [hunk 4]
```diff
@@ -28,17 +28,36 @@
...
 
         {:keys [server-socket port] :as server}
         (nrepl.server/start-server :handler handler
-                                   :bind bind
-                                   :port port)
+                                   :bind (or bind "localhost")
```
Comment (bbatsov) [inline src/cider_nrepl/main.clj]: Doesn't bind work with `nil`?

File: test/clj/cider/nrepl/main_test.clj (hunk 1 above)
Comment (hagmonk) [reply test/clj/cider/nrepl/main_test.clj]: My understanding was that the `with-open` macro would suffice to close the server. I borrowed much of this from `cider.nrepl.middleware.debug-integration-test/with-nrepl-session*`

File: src/cider_nrepl/main.clj (hunk 2 above)
Comment (hagmonk) [reply src/cider_nrepl/main.clj]: I see, so that implies that either a handler or middleware is expected, but not both. I can make that change.

File: src/cider_nrepl/main.clj (hunk 4 above)
Comment (hagmonk) [reply src/cider_nrepl/main.clj]: So, I think what will happen here is an exception when this goes through travis. From `clojure.tools.nrepl.server`:

```
 (let [bind-addr (if bind
                    (InetSocketAddress. ^String bind ^Integer port)
                    (let [local (InetSocketAddress. "::" port)]
                      (if (.isUnresolved local)
                        (InetSocketAddress. "localhost" port)
                        local)))
```

`nil` causes `(InetSocketAddress. "::" port)` to be invoked, which throws an exception in travis - I presume due to IPv6 not being enabled. If we default to localhost, we dodge that particular idiosyncrasy.

Comment (hagmonk) [reply src/cider_nrepl/main.clj]: Sorry I should clarify: I made this change after experiencing the exception in travis. Not a thought experiment, but an observation :)

File: test/clj/cider/nrepl/main_test.clj (hunk 1 above)
Comment (bbatsov) [reply test/clj/cider/nrepl/main_test.clj]: Ah, ok.

File: src/cider_nrepl/main.clj (hunk 2 above)
Comment (bbatsov) [reply src/cider_nrepl/main.clj]: Yeah, exactly. Normally you'd just use a predefined handler, but in some cases you might opt to build the handler yourself by supplying some list of middlewares instead.

Comment (bbatsov) [reply src/cider_nrepl/main.clj]: (e.g. because some middleware is problematic in your setup or something like this)

File: src/cider_nrepl/main.clj (hunk 4 above)
Comment (bbatsov) [reply src/cider_nrepl/main.clj]: I see. I was just wondering if this won't message up something for people who have disabled IPv4. Probably not a big deal now, I'll fixed this once we finally move the project to https://github.com/nrepl/nREPL

Comment (bbatsov) [reply src/cider_nrepl/main.clj]: (tools.nrepl is practically dead, so we've migrated the project out of clojure contrib to revive it)
